### ISSUE TITLE
Any plans to add subscribe (modbus write?)

### ISSUE THREAD

**Issue by nzfarmer1** [owagner/modbus2mqtt#1]
thanks

**Comment by owagner** [comment]
I don't have a use-case for that myself, but it's easy to do and I'd happily merge a patch

**Comment by nzfarmer1** [comment]
I have it working here but untested on PLC. Will forward soon.

prefix/write/<slaveid>/<fc>/<register>

where fc in (5,6)

**Comment by owagner** [comment]
Cool. Could you make that prefix/set/ to be in line with the mqtt-smarthome suggestion?

**Comment by nzfarmer1** [comment]
Done.

Please see: 

https://github.com/nzfarmer1/modbus2mqtt/tree/feature/addsetters

**Comment by owagner** [comment]
Cool. Would you mind sending this as a pull request, so I can more easily merge?

(minor niggle: use logging.warning instead of .info when getting a message with wrong fc/reg)

**Comment by owagner** [comment]
PR sent & merged
